# Generated by Django 4.0.6 on 2022-07-27 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerece_main', '0002_nfts'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfts',
            name='product_buy',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ecommerece_main.products'),
            preserve_default=False,
        ),
    ]
