# Generated by Django 4.0.6 on 2022-08-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerece_main', '0005_alter_wallet_details_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet_details',
            name='wallet_address',
            field=models.CharField(max_length=34),
        ),
    ]
