# Generated by Django 4.0.6 on 2022-08-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerece_main', '0006_alter_wallet_details_wallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet_details',
            name='wallet_address',
            field=models.CharField(max_length=42),
        ),
    ]
